version: "2"

services:
  apache:
    image: eboraas/apache
    volumes:
      - ./status.conf:/etc/apache2/mods-enabled/status.conf
    ports:
      - "9002:80"
    networks:
      - apache

  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
      - "8083:8083"
    networks:
      - influxdb

  telegraf:
    image: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    links:
      - apache
    networks:
      - influxdb
      - apache

  grafana:
    image: grafana/grafana
    links:
      - influxdb
    ports:
      - "3000:3000"

networks:
  influxdb:
    driver: bridge
  apache:
    driver: bridge
