telegraf:
  image: telegraf
  container_name: telegraf 
  volumes:
   - ./telegraf.conf:/etc/opt/influxdb/telegraf.conf:ro
  links:
    - influxdb

apache:
  image: eboraas/apache
  container_name: apache 
  volumes:
   - ./status.conf:/etc/apache2/mods-enabled/status.conf
  links:
    - telegraf
  ports:
    - "9002:80"

influxdb:
  image: influxdb
  container_name: influxdb
  ports:
    - "8086:8086"
    - "8083:8083"

grafana:
  image: grafana/grafana
  container_name: grafana
  links:
    - influxdb
  ports:
    - "3000:3000"
