version: '2'

services:
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
      - "8083:8083"
    networks:
      - influxdb

  telegraf:
    image: telegraf
    extra_hosts:
      - 'apache:$IP'
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - influxdb

  grafana:
    image: grafana/grafana
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_DASHBOARDS_JSON_ENABLED=true

networks:
  influxdb:
    driver: bridge
